services:
  db:
    image: postgres:16
    container_name: cheguei-bem-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: camila
      POSTGRES_PASSWORD: troque_essa_senha
      POSTGRES_DB: cheguei_bem
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: