CREATE TABLE usuarias (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  senha_hash TEXT NOT NULL,
  criada_em TIMESTAMP DEFAULT NOW()
);

CREATE TABLE contatos (
  id SERIAL PRIMARY KEY,
  usuaria_id INTEGER NOT NULL REFERENCES usuarias(id) ON DELETE CASCADE,
  nome VARCHAR(100) NOT NULL,
  telefone VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS trajetos (
  id SERIAL PRIMARY KEY,
  usuaria_id INTEGER NOT NULL REFERENCES usuarias(id) ON DELETE CASCADE,
  destino VARCHAR(150),
  saida_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  previsao_chegada TIMESTAMPTZ NOT NULL,
  chegada_em TIMESTAMPTZ,
  status VARCHAR(20) NOT NULL DEFAULT 'em_andamento',
  token_publico VARCHAR(64) UNIQUE NOT NULL,
  expira_em TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS posicoes (
  id SERIAL PRIMARY KEY,
  trajeto_id INTEGER NOT NULL REFERENCES trajetos(id) ON DELETE CASCADE,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  registrada_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);